<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-248P7JL" failures="1" tests="3" name="Entrata-Test" time="52.967" errors="0" timestamp="2024-09-22T19:03:03 IST">
  <testcase classname="test.EntrataTest" name="verifyAlreadyRegisterFUnctionalityWithIncorrectDetails" time="15.866">
    <failure type="java.lang.AssertionError" message="expected [This confirmation number doesn&amp;apos;t exist.] but found [You&amp;apos;ve reached your maximum number of login attempts. Contact the event planner to continue.]">
      <![CDATA[java.lang.AssertionError: expected [This confirmation number doesn't exist.] but found [You've reached your maximum number of login attempts. Contact the event planner to continue.]
at test.EntrataTest.verifyAlreadyRegisterFUnctionalityWithIncorrectDetails(EntrataTest.java:138)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- verifyAlreadyRegisterFUnctionalityWithIncorrectDetails -->
  <testcase classname="test.EntrataTest" name="verifyProductListOfEntrataWebsite" time="5.07"/>
  <testcase classname="test.EntrataTest" name="verifyScheduleDemoFormForEntrataWebsite" time="4.46"/>
</testsuite> <!-- Entrata-Test -->
